### ISSUE TITLE
Missing error handling results in no feedback to user

### ISSUE THREAD

**Issue by lambada** [greys-bots/hubbot#1] opened 2020-03-03 19:30 UTC
Our guild is trying to use this bot, and the following commands seem to be hanging with no visible output
- hub!config banlog _channel_
- hub!export (which gets the hourglass but no DM ever arrives).

After looking through the source code it looks like in some circumstances promises aren't resolving, causing the bot to appear to 'hang' to a user.

For the first command it looks like if the query to the DB fails, the promise is not resolved
https://github.com/greys-bots/hubbot/blob/20ba5b8044944bc00f528ac8b4d5a4b2b654bd35/utils/configs.js#L29
That results in the code following https://github.com/greys-bots/hubbot/blob/f2fe221f2f448a3a48c652615c7e527e20e93633/commands/Bot%20and%20Server%20Customization/config.js#L42 never executing, and so no message being written to the channel.

Similarly over in getExportData https://github.com/greys-bots/hubbot/blob/20ba5b8044944bc00f528ac8b4d5a4b2b654bd35/utils/import%20and%20export.js#L4 if any of the awaits throw then the entire outer promise would reject leading to no config at all being send up the chain
And when that the reaches the outer command handling of https://github.com/greys-bots/hubbot/blob/f2fe221f2f448a3a48c652615c7e527e20e93633/commands/Utility/export.js#L6
It again would throw which results in the hourglass remaining, but no further visible output.

I haven't worked out _why_ our config in your DB is bad enough to cause these fails (we're using the pk instance), but these are still problems.

**Comment by selenated** [comment] 2020-04-13 02:45
Ahh, sorry we didn't see this sooner! We're currently working on rewriting all of the code (starting with the public version of this bot, [Alex](https://github.com/greys-bots/alex), first). These problems will be fixed once that's done. In the meantime I'll go ahead and try to push a fix tomorrow, and see if we can figure out a way to get your config fixed. There's a chance that the problem is related to columns in the database (we were updating those silently, since we didn't know others were using the bot; sorry about that) if that helps any

Sorry for the inconvenience, and thank you for bringing this to our attention!

**Comment by selenated** [comment] 2020-04-13 15:17
Update: whoops, that was all on us. Forgot to remove some extra question marks in the code to create a new config :')
Pretty sure I also misinterpreted part of your post, which is also my bad 😔
Either way, should be fixed now! Sorry about that

**Closed as completed** 2020-04-13 15:17 UTC
